### ISSUE TITLE
source ~/.vimrc error after installation

### ISSUE THREAD

**Issue by Erichliu00** [ryanb/dotfiles#34]
Hi, after installation, run `source ~/.vimrc` cause following error:

> ~/.dotfiles[master*]% source ~/.vimrc
> /home/haoliu/.vimrc:1: no matches found: (much better!).
> /home/haoliu/.vimrc:4: command not found:  This must be first, because it changes other options as a side effect.\nset nocompatible\n\n
> /home/haoliu/.vimrc:17: command not found:  Don't use Ex mode, use Q for formatting\nmap Q gq\n\n
> /home/haoliu/.vimrc:21: command not found:  text is lost and it only works for putting the current register.\nvnoremap
> /home/haoliu/.vimrc:25: command not found:  Also switch on highlighting the last used search pattern.\nif (&t_Co > 2 || has(gui_running)) && !exists(syntax_on)\n  syntax on\n  set hlsearch\nendif\n\n
> /home/haoliu/.vimrc:34: command not found:  Only do this part when compiled with support for autocommands.\nif has(autocmd)\n  
> /home/haoliu/.vimrc:37: command not found:  Use the default filetype settings, so that mail gets 'tw' set to 72,\n  
> /home/haoliu/.vimrc:39: command not found:  Also load indent files, to automatically do language-dependent indenting.\n  filetype plugin indent on\n\n  
> /home/haoliu/.vimrc:43: no matches found: *.txt
> /home/haoliu/.vimrc:45: command not found:  Enable soft-wrapping for text files\n  autocmd FileType text,markdown,html,xhtml,eruby setlocal wrap linebreak nolist\n\n  
> /home/haoliu/.vimrc:49: command not found: augroup
> /home/haoliu/.vimrc:50: command not found: au!
> /home/haoliu/.vimrc:52: command not found:  For all text files set 'textwidth' to 78 characters.\n  
> /home/haoliu/.vimrc:55: no matches found: Dont do it when the position is invalid or when inside an event handler\n  " (happens when dropping a file on gvim).\n  autocmd BufReadPost *\n    \ if line("") > 0 && line(\"") <= line("$") |\n    \   exe "normal g`\"" |\n    \ endif\n\n  " Automatically load .vimrc source when saved\n  autocmd BufWritePost .vimrc source $MYVIMRC\n\n  augroup END\n\nelse\n\n  set autoindent\t\t" always set autoindenting on\n\nendif " has("autocmd")\n\n" if has("folding")\n  " set foldenable\n  " set foldmethod=syntax\n  " set foldlevel=1\n  " set foldnestmax=2\n  " set foldtext=strpart(getline(v:foldstart),0,50). ... .substitute(getline(v:foldend),^[ #]*,,g). \n" endif\n\n" Softtabs, 2 spaces\nset tabstop=2\nset shiftwidth=2\nset expandtab\n\n" Always display the status line\nset laststatus=2\n\n" \ is the leader character\nlet mapleader = ","\n\n" Edit the README_FOR_APP (makes :R commands work)\nmap <Leader>R :e doc/README_FOR_APP<CR>\n\n" Leader shortcuts for Rails commands\nmap <Leader>m :Rmodel \nmap <Leader>c :Rcontroller \nmap <Leader>v :Rview \nmap <Leader>u :Runittest \nmap <Leader>f :Rfunctionaltest \nmap <Leader>tm :RTmodel \nmap <Leader>tc :RTcontroller \nmap <Leader>tv :RTview \nmap <Leader>tu :RTunittest \nmap <Leader>tf :RTfunctionaltest \nmap <Leader>sm :RSmodel \nmap <Leader>sc :RScontroller \nmap <Leader>sv :RSview \nmap <Leader>su :RSunittest \nmap <Leader>sf :RSfunctionaltest \n\n" Hide search highlighting\nmap <Leader>h :set invhls <CR>\n\n" Opens an edit command with the path of the currently edited file filled in\n" Normal mode: <Leader>e\nmap <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>\n\n" Opens a tab edit command with the path of the currently edited file filled in\n" Normal mode: <Leader>t\nmap <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>\n\n" Inserts the path of the currently edited file into a command\n" Command mode: Ctrl+P\ncmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>\n\n" Duplicate a selection\n" Visual mode: D\nvmap D y
> /home/haoliu/.vimrc:132: command not found:  Press Shift+P while in visual mode to replace the selection without\n
> /home/haoliu/.vimrc:135: parse error near `\n'

Although vim work fine even with this, I wonder if you can help me solve this.

**Comment by seefood** [comment]
.vimrc is not a shell script, and is not meant to be sourced from the shell. it's run by .vimrc at program start.

**Comment by Erichliu00** [comment]
Oh, I see, thank you.
